### ISSUE TITLE
Broken ui when log viewer is shrinked

### ISSUE THREAD

**Issue by lstocchi** [vscode-kubernetes-tools/vscode-kubernetes-tools#1093]
![image](https://user-images.githubusercontent.com/49404737/174322796-b4f65413-a9ab-42b4-b1ec-e92160055ad2.png)

**Comment by Tatsinnit** [comment]
💡❤️ Hiya and thank you so much for this, fyi and cc for more thoughts and ideas @lstocchi , below is how it behaves for me and seems like this is fixed, wondering if we can double check. 

<img width="1211" alt="Screenshot 2023-06-16 at 12 21 52 PM" src="https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/assets/6233295/d54df3e3-032f-48ad-9c71-fb28336cb69d">

**Comment by lstocchi** [comment]
@Tatsinnit yes, it still happen to me. Try to shrink the webview.

![log-vscode-k8s-break](https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/assets/49404737/de4e5c34-9134-4714-ac39-686cb3eeba06)

**Comment by Tatsinnit** [comment]
thank you so much @mikeseese for this PR which fixes this issue, : https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/pull/1205 

Shall we close this issue? :) <3

**Comment by mikeseese** [comment]
Yes, my PR should have closed this one.
